name: "0x157"

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: "Try Hack me Badge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "0x157"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
